// config keys
export const DPH_OPENAI_INIT_CONFIG_JSON = 'DPH_OPENAI_INIT_CONFIG_JSON';
export const DPH_MODEL_NAME = 'DPH_MODEL_NAME';
export const DPH_LANGSMITH_DEBUG = 'DPH_LANGSMITH_DEBUG';
export const DPH_DEBUG_AI_PROFILE = 'DPH_DEBUG_AI_PROFILE';
export const DPH_DEBUG_AI_RESPONSE = 'DPH_DEBUG_AI_RESPONSE';
export const DPH_DANGEROUSLY_PRINT_ALL_CONFIG =
  'DPH_DANGEROUSLY_PRINT_ALL_CONFIG';
export const DPH_DEBUG_MODE = 'DPH_DEBUG_MODE';
export const DPH_MCP_USE_PUPPETEER_MODE = 'DPH_MCP_USE_PUPPETEER_MODE';
export const DPH_MCP_CHROME_PATH = 'DPH_MCP_CHROME_PATH';
export const DPH_MCP_ANDROID_MODE = 'DPH_MCP_ANDROID_MODE';
export const DOCKER_CONTAINER = 'DOCKER_CONTAINER';
export const DPH_FORCE_DEEP_THINK = 'DPH_FORCE_DEEP_THINK';

export const DPH_OPENAI_SOCKS_PROXY = 'DPH_OPENAI_SOCKS_PROXY';
export const DPH_OPENAI_HTTP_PROXY = 'DPH_OPENAI_HTTP_PROXY';
export const OPENAI_API_KEY = 'OPENAI_API_KEY';
export const OPENAI_BASE_URL = 'OPENAI_BASE_URL';
export const OPENAI_MAX_TOKENS = 'OPENAI_MAX_TOKENS';

export const DPH_ADB_PATH = 'DPH_ADB_PATH';
export const DPH_ADB_REMOTE_HOST = 'DPH_ADB_REMOTE_HOST';
export const DPH_ADB_REMOTE_PORT = 'DPH_ADB_REMOTE_PORT';
export const DPH_ANDROID_IME_STRATEGY = 'DPH_ANDROID_IME_STRATEGY';

export const DPH_IOS_DEVICE_UDID = 'DPH_IOS_DEVICE_UDID';
export const DPH_IOS_SIMULATOR_UDID = 'DPH_IOS_SIMULATOR_UDID';

export const DPH_CACHE = 'DPH_CACHE';
export const DPH_USE_VLM_UI_TARS = 'DPH_USE_VLM_UI_TARS';
export const DPH_USE_QWEN_VL = 'DPH_USE_QWEN_VL';
export const DPH_USE_QWEN3_VL = 'DPH_USE_QWEN3_VL';
export const DPH_USE_DOUBAO_VISION = 'DPH_USE_DOUBAO_VISION';
export const DPH_USE_GEMINI = 'DPH_USE_GEMINI';
export const DPH_USE_VL_MODEL = 'DPH_USE_VL_MODEL';
export const MATCH_BY_POSITION = 'MATCH_BY_POSITION';
export const DPH_API_TYPE = 'DPH-API-TYPE';
export const DPH_REPORT_TAG_NAME = 'DPH_REPORT_TAG_NAME';

export const DPH_REPLANNING_CYCLE_LIMIT = 'DPH_REPLANNING_CYCLE_LIMIT';

export const DPH_PREFERRED_LANGUAGE = 'DPH_PREFERRED_LANGUAGE';

export const DPH_USE_AZURE_OPENAI = 'DPH_USE_AZURE_OPENAI';
export const DPH_AZURE_OPENAI_SCOPE = 'DPH_AZURE_OPENAI_SCOPE';
export const DPH_AZURE_OPENAI_INIT_CONFIG_JSON =
  'DPH_AZURE_OPENAI_INIT_CONFIG_JSON';

export const DPH_CACHE_MAX_FILENAME_LENGTH = 'DPH_CACHE_MAX_FILENAME_LENGTH';

export const AZURE_OPENAI_ENDPOINT = 'AZURE_OPENAI_ENDPOINT';
export const AZURE_OPENAI_KEY = 'AZURE_OPENAI_KEY';
export const AZURE_OPENAI_API_VERSION = 'AZURE_OPENAI_API_VERSION';
export const AZURE_OPENAI_DEPLOYMENT = 'AZURE_OPENAI_DEPLOYMENT';

export const DPH_USE_ANTHROPIC_SDK = 'DPH_USE_ANTHROPIC_SDK';
export const ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY';

export const DPH_RUN_DIR = 'DPH_RUN_DIR';

// default new
export const DPH_OPENAI_BASE_URL = 'DPH_OPENAI_BASE_URL';
export const DPH_OPENAI_API_KEY = 'DPH_OPENAI_API_KEY';
export const DPH_OPENAI_USE_AZURE = 'DPH_OPENAI_USE_AZURE';
export const DPH_AZURE_OPENAI_KEY = 'DPH_AZURE_OPENAI_KEY';
export const DPH_AZURE_OPENAI_ENDPOINT = 'DPH_AZURE_OPENAI_ENDPOINT';
export const DPH_AZURE_OPENAI_API_VERSION = 'DPH_AZURE_OPENAI_API_VERSION';
export const DPH_AZURE_OPENAI_DEPLOYMENT = 'DPH_AZURE_OPENAI_DEPLOYMENT';
export const DPH_ANTHROPIC_API_KEY = 'DPH_ANTHROPIC_API_KEY';
export const DPH_VL_MODE = 'DPH_VL_MODE';

// VQA
export const DPH_VQA_MODEL_NAME = 'DPH_VQA_MODEL_NAME';
export const DPH_VQA_OPENAI_SOCKS_PROXY = 'DPH_VQA_OPENAI_SOCKS_PROXY';
export const DPH_VQA_OPENAI_HTTP_PROXY = 'DPH_VQA_OPENAI_HTTP_PROXY';
export const DPH_VQA_OPENAI_BASE_URL = 'DPH_VQA_OPENAI_BASE_URL';
export const DPH_VQA_OPENAI_API_KEY = 'DPH_VQA_OPENAI_API_KEY';
export const DPH_VQA_OPENAI_INIT_CONFIG_JSON =
  'DPH_VQA_OPENAI_INIT_CONFIG_JSON';
export const DPH_VQA_OPENAI_USE_AZURE = 'DPH_VQA_OPENAI_USE_AZURE';
export const DPH_VQA_USE_AZURE_OPENAI = 'DPH_VQA_USE_AZURE_OPENAI';
export const DPH_VQA_AZURE_OPENAI_SCOPE = 'DPH_VQA_AZURE_OPENAI_SCOPE';
export const DPH_VQA_AZURE_OPENAI_KEY = 'DPH_VQA_AZURE_OPENAI_KEY';
export const DPH_VQA_AZURE_OPENAI_ENDPOINT = 'DPH_VQA_AZURE_OPENAI_ENDPOINT';
export const DPH_VQA_AZURE_OPENAI_API_VERSION =
  'DPH_VQA_AZURE_OPENAI_API_VERSION';
export const DPH_VQA_AZURE_OPENAI_DEPLOYMENT =
  'DPH_VQA_AZURE_OPENAI_DEPLOYMENT';
export const DPH_VQA_AZURE_OPENAI_INIT_CONFIG_JSON =
  'DPH_VQA_AZURE_OPENAI_INIT_CONFIG_JSON';
export const DPH_VQA_USE_ANTHROPIC_SDK = 'DPH_VQA_USE_ANTHROPIC_SDK';
export const DPH_VQA_ANTHROPIC_API_KEY = 'DPH_VQA_ANTHROPIC_API_KEY';
export const DPH_VQA_VL_MODE = 'DPH_VQA_VL_MODE';

// PLANNING
export const DPH_PLANNING_MODEL_NAME = 'DPH_PLANNING_MODEL_NAME';
export const DPH_PLANNING_OPENAI_SOCKS_PROXY =
  'DPH_PLANNING_OPENAI_SOCKS_PROXY';
export const DPH_PLANNING_OPENAI_HTTP_PROXY = 'DPH_PLANNING_OPENAI_HTTP_PROXY';
export const DPH_PLANNING_OPENAI_BASE_URL = 'DPH_PLANNING_OPENAI_BASE_URL';
export const DPH_PLANNING_OPENAI_API_KEY = 'DPH_PLANNING_OPENAI_API_KEY';
export const DPH_PLANNING_OPENAI_INIT_CONFIG_JSON =
  'DPH_PLANNING_OPENAI_INIT_CONFIG_JSON';
export const DPH_PLANNING_OPENAI_USE_AZURE = 'DPH_PLANNING_OPENAI_USE_AZURE';
export const DPH_PLANNING_USE_AZURE_OPENAI = 'DPH_PLANNING_USE_AZURE_OPENAI';
export const DPH_PLANNING_AZURE_OPENAI_SCOPE =
  'DPH_PLANNING_AZURE_OPENAI_SCOPE';
export const DPH_PLANNING_AZURE_OPENAI_KEY = 'DPH_PLANNING_AZURE_OPENAI_KEY';
export const DPH_PLANNING_AZURE_OPENAI_ENDPOINT =
  'DPH_PLANNING_AZURE_OPENAI_ENDPOINT';
export const DPH_PLANNING_AZURE_OPENAI_API_VERSION =
  'DPH_PLANNING_AZURE_OPENAI_API_VERSION';
export const DPH_PLANNING_AZURE_OPENAI_DEPLOYMENT =
  'DPH_PLANNING_AZURE_OPENAI_DEPLOYMENT';
export const DPH_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON =
  'DPH_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON';
export const DPH_PLANNING_USE_ANTHROPIC_SDK = 'DPH_PLANNING_USE_ANTHROPIC_SDK';
export const DPH_PLANNING_ANTHROPIC_API_KEY = 'DPH_PLANNING_ANTHROPIC_API_KEY';
export const DPH_PLANNING_VL_MODE = 'DPH_PLANNING_VL_MODE';

// GROUNDING
export const DPH_GROUNDING_MODEL_NAME = 'DPH_GROUNDING_MODEL_NAME';
export const DPH_GROUNDING_OPENAI_SOCKS_PROXY =
  'DPH_GROUNDING_OPENAI_SOCKS_PROXY';
export const DPH_GROUNDING_OPENAI_HTTP_PROXY =
  'DPH_GROUNDING_OPENAI_HTTP_PROXY';
export const DPH_GROUNDING_OPENAI_BASE_URL = 'DPH_GROUNDING_OPENAI_BASE_URL';
export const DPH_GROUNDING_OPENAI_API_KEY = 'DPH_GROUNDING_OPENAI_API_KEY';
export const DPH_GROUNDING_OPENAI_INIT_CONFIG_JSON =
  'DPH_GROUNDING_OPENAI_INIT_CONFIG_JSON';
export const DPH_GROUNDING_OPENAI_USE_AZURE = 'DPH_GROUNDING_OPENAI_USE_AZURE';
export const DPH_GROUNDING_USE_AZURE_OPENAI = 'DPH_GROUNDING_USE_AZURE_OPENAI';
export const DPH_GROUNDING_AZURE_OPENAI_SCOPE =
  'DPH_GROUNDING_AZURE_OPENAI_SCOPE';
export const DPH_GROUNDING_AZURE_OPENAI_KEY = 'DPH_GROUNDING_AZURE_OPENAI_KEY';
export const DPH_GROUNDING_AZURE_OPENAI_ENDPOINT =
  'DPH_GROUNDING_AZURE_OPENAI_ENDPOINT';
export const DPH_GROUNDING_AZURE_OPENAI_API_VERSION =
  'DPH_GROUNDING_AZURE_OPENAI_API_VERSION';
export const DPH_GROUNDING_AZURE_OPENAI_DEPLOYMENT =
  'DPH_GROUNDING_AZURE_OPENAI_DEPLOYMENT';
export const DPH_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON =
  'DPH_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON';
export const DPH_GROUNDING_USE_ANTHROPIC_SDK =
  'DPH_GROUNDING_USE_ANTHROPIC_SDK';
export const DPH_GROUNDING_ANTHROPIC_API_KEY =
  'DPH_GROUNDING_ANTHROPIC_API_KEY';
export const DPH_GROUNDING_VL_MODE = 'DPH_GROUNDING_VL_MODE';

// @deprecated
export const OPENAI_USE_AZURE = 'OPENAI_USE_AZURE';

// Legacy aliases for backward compatibility
export const MIDSCENE_OPENAI_INIT_CONFIG_JSON = DPH_OPENAI_INIT_CONFIG_JSON;
export const MIDSCENE_MODEL_NAME = DPH_MODEL_NAME;
export const MIDSCENE_LANGSMITH_DEBUG = DPH_LANGSMITH_DEBUG;
export const MIDSCENE_DEBUG_AI_PROFILE = DPH_DEBUG_AI_PROFILE;
export const MIDSCENE_DEBUG_AI_RESPONSE = DPH_DEBUG_AI_RESPONSE;
export const MIDSCENE_DANGEROUSLY_PRINT_ALL_CONFIG =
  DPH_DANGEROUSLY_PRINT_ALL_CONFIG;
export const MIDSCENE_DEBUG_MODE = DPH_DEBUG_MODE;
export const MIDSCENE_MCP_USE_PUPPETEER_MODE = DPH_MCP_USE_PUPPETEER_MODE;
export const MIDSCENE_MCP_CHROME_PATH = DPH_MCP_CHROME_PATH;
export const MIDSCENE_MCP_ANDROID_MODE = DPH_MCP_ANDROID_MODE;
export const MIDSCENE_FORCE_DEEP_THINK = DPH_FORCE_DEEP_THINK;
export const MIDSCENE_OPENAI_SOCKS_PROXY = DPH_OPENAI_SOCKS_PROXY;
export const MIDSCENE_OPENAI_HTTP_PROXY = DPH_OPENAI_HTTP_PROXY;
export const MIDSCENE_ADB_PATH = DPH_ADB_PATH;
export const MIDSCENE_ADB_REMOTE_HOST = DPH_ADB_REMOTE_HOST;
export const MIDSCENE_ADB_REMOTE_PORT = DPH_ADB_REMOTE_PORT;
export const MIDSCENE_ANDROID_IME_STRATEGY = DPH_ANDROID_IME_STRATEGY;
export const MIDSCENE_IOS_DEVICE_UDID = DPH_IOS_DEVICE_UDID;
export const MIDSCENE_IOS_SIMULATOR_UDID = DPH_IOS_SIMULATOR_UDID;
export const MIDSCENE_CACHE = DPH_CACHE;
export const MIDSCENE_USE_VLM_UI_TARS = DPH_USE_VLM_UI_TARS;
export const MIDSCENE_USE_QWEN_VL = DPH_USE_QWEN_VL;
export const MIDSCENE_USE_QWEN3_VL = DPH_USE_QWEN3_VL;
export const MIDSCENE_USE_DOUBAO_VISION = DPH_USE_DOUBAO_VISION;
export const MIDSCENE_USE_GEMINI = DPH_USE_GEMINI;
export const MIDSCENE_USE_VL_MODEL = DPH_USE_VL_MODEL;
export const MIDSCENE_API_TYPE = DPH_API_TYPE;
export const MIDSCENE_REPORT_TAG_NAME = DPH_REPORT_TAG_NAME;
export const MIDSCENE_REPLANNING_CYCLE_LIMIT = DPH_REPLANNING_CYCLE_LIMIT;
export const MIDSCENE_PREFERRED_LANGUAGE = DPH_PREFERRED_LANGUAGE;
export const MIDSCENE_USE_AZURE_OPENAI = DPH_USE_AZURE_OPENAI;
export const MIDSCENE_AZURE_OPENAI_SCOPE = DPH_AZURE_OPENAI_SCOPE;
export const MIDSCENE_AZURE_OPENAI_INIT_CONFIG_JSON =
  DPH_AZURE_OPENAI_INIT_CONFIG_JSON;
export const MIDSCENE_CACHE_MAX_FILENAME_LENGTH = DPH_CACHE_MAX_FILENAME_LENGTH;
export const MIDSCENE_USE_ANTHROPIC_SDK = DPH_USE_ANTHROPIC_SDK;
export const MIDSCENE_RUN_DIR = DPH_RUN_DIR;
export const MIDSCENE_OPENAI_BASE_URL = DPH_OPENAI_BASE_URL;
export const MIDSCENE_OPENAI_API_KEY = DPH_OPENAI_API_KEY;
export const MIDSCENE_OPENAI_USE_AZURE = DPH_OPENAI_USE_AZURE;
export const MIDSCENE_AZURE_OPENAI_KEY = DPH_AZURE_OPENAI_KEY;
export const MIDSCENE_AZURE_OPENAI_ENDPOINT = DPH_AZURE_OPENAI_ENDPOINT;
export const MIDSCENE_AZURE_OPENAI_API_VERSION = DPH_AZURE_OPENAI_API_VERSION;
export const MIDSCENE_AZURE_OPENAI_DEPLOYMENT = DPH_AZURE_OPENAI_DEPLOYMENT;
export const MIDSCENE_ANTHROPIC_API_KEY = DPH_ANTHROPIC_API_KEY;
export const MIDSCENE_VL_MODE = DPH_VL_MODE;
export const MIDSCENE_VQA_MODEL_NAME = DPH_VQA_MODEL_NAME;
export const MIDSCENE_VQA_OPENAI_SOCKS_PROXY = DPH_VQA_OPENAI_SOCKS_PROXY;
export const MIDSCENE_VQA_OPENAI_HTTP_PROXY = DPH_VQA_OPENAI_HTTP_PROXY;
export const MIDSCENE_VQA_OPENAI_BASE_URL = DPH_VQA_OPENAI_BASE_URL;
export const MIDSCENE_VQA_OPENAI_API_KEY = DPH_VQA_OPENAI_API_KEY;
export const MIDSCENE_VQA_OPENAI_INIT_CONFIG_JSON =
  DPH_VQA_OPENAI_INIT_CONFIG_JSON;
export const MIDSCENE_VQA_OPENAI_USE_AZURE = DPH_VQA_OPENAI_USE_AZURE;
export const MIDSCENE_VQA_USE_AZURE_OPENAI = DPH_VQA_USE_AZURE_OPENAI;
export const MIDSCENE_VQA_AZURE_OPENAI_SCOPE = DPH_VQA_AZURE_OPENAI_SCOPE;
export const MIDSCENE_VQA_AZURE_OPENAI_KEY = DPH_VQA_AZURE_OPENAI_KEY;
export const MIDSCENE_VQA_AZURE_OPENAI_ENDPOINT = DPH_VQA_AZURE_OPENAI_ENDPOINT;
export const MIDSCENE_VQA_AZURE_OPENAI_API_VERSION =
  DPH_VQA_AZURE_OPENAI_API_VERSION;
export const MIDSCENE_VQA_AZURE_OPENAI_DEPLOYMENT =
  DPH_VQA_AZURE_OPENAI_DEPLOYMENT;
export const MIDSCENE_VQA_AZURE_OPENAI_INIT_CONFIG_JSON =
  DPH_VQA_AZURE_OPENAI_INIT_CONFIG_JSON;
export const MIDSCENE_VQA_USE_ANTHROPIC_SDK = DPH_VQA_USE_ANTHROPIC_SDK;
export const MIDSCENE_VQA_ANTHROPIC_API_KEY = DPH_VQA_ANTHROPIC_API_KEY;
export const MIDSCENE_VQA_VL_MODE = DPH_VQA_VL_MODE;
export const MIDSCENE_PLANNING_MODEL_NAME = DPH_PLANNING_MODEL_NAME;
export const MIDSCENE_PLANNING_OPENAI_SOCKS_PROXY =
  DPH_PLANNING_OPENAI_SOCKS_PROXY;
export const MIDSCENE_PLANNING_OPENAI_HTTP_PROXY =
  DPH_PLANNING_OPENAI_HTTP_PROXY;
export const MIDSCENE_PLANNING_OPENAI_BASE_URL = DPH_PLANNING_OPENAI_BASE_URL;
export const MIDSCENE_PLANNING_OPENAI_API_KEY = DPH_PLANNING_OPENAI_API_KEY;
export const MIDSCENE_PLANNING_OPENAI_INIT_CONFIG_JSON =
  DPH_PLANNING_OPENAI_INIT_CONFIG_JSON;
export const MIDSCENE_PLANNING_OPENAI_USE_AZURE = DPH_PLANNING_OPENAI_USE_AZURE;
export const MIDSCENE_PLANNING_USE_AZURE_OPENAI = DPH_PLANNING_USE_AZURE_OPENAI;
export const MIDSCENE_PLANNING_AZURE_OPENAI_SCOPE =
  DPH_PLANNING_AZURE_OPENAI_SCOPE;
export const MIDSCENE_PLANNING_AZURE_OPENAI_KEY = DPH_PLANNING_AZURE_OPENAI_KEY;
export const MIDSCENE_PLANNING_AZURE_OPENAI_ENDPOINT =
  DPH_PLANNING_AZURE_OPENAI_ENDPOINT;
export const MIDSCENE_PLANNING_AZURE_OPENAI_API_VERSION =
  DPH_PLANNING_AZURE_OPENAI_API_VERSION;
export const MIDSCENE_PLANNING_AZURE_OPENAI_DEPLOYMENT =
  DPH_PLANNING_AZURE_OPENAI_DEPLOYMENT;
export const MIDSCENE_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON =
  DPH_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON;
export const MIDSCENE_PLANNING_USE_ANTHROPIC_SDK =
  DPH_PLANNING_USE_ANTHROPIC_SDK;
export const MIDSCENE_PLANNING_ANTHROPIC_API_KEY =
  DPH_PLANNING_ANTHROPIC_API_KEY;
export const MIDSCENE_PLANNING_VL_MODE = DPH_PLANNING_VL_MODE;
export const MIDSCENE_GROUNDING_MODEL_NAME = DPH_GROUNDING_MODEL_NAME;
export const MIDSCENE_GROUNDING_OPENAI_SOCKS_PROXY =
  DPH_GROUNDING_OPENAI_SOCKS_PROXY;
export const MIDSCENE_GROUNDING_OPENAI_HTTP_PROXY =
  DPH_GROUNDING_OPENAI_HTTP_PROXY;
export const MIDSCENE_GROUNDING_OPENAI_BASE_URL = DPH_GROUNDING_OPENAI_BASE_URL;
export const MIDSCENE_GROUNDING_OPENAI_API_KEY = DPH_GROUNDING_OPENAI_API_KEY;
export const MIDSCENE_GROUNDING_OPENAI_INIT_CONFIG_JSON =
  DPH_GROUNDING_OPENAI_INIT_CONFIG_JSON;
export const MIDSCENE_GROUNDING_OPENAI_USE_AZURE =
  DPH_GROUNDING_OPENAI_USE_AZURE;
export const MIDSCENE_GROUNDING_USE_AZURE_OPENAI =
  DPH_GROUNDING_USE_AZURE_OPENAI;
export const MIDSCENE_GROUNDING_AZURE_OPENAI_SCOPE =
  DPH_GROUNDING_AZURE_OPENAI_SCOPE;
export const MIDSCENE_GROUNDING_AZURE_OPENAI_KEY =
  DPH_GROUNDING_AZURE_OPENAI_KEY;
export const MIDSCENE_GROUNDING_AZURE_OPENAI_ENDPOINT =
  DPH_GROUNDING_AZURE_OPENAI_ENDPOINT;
export const MIDSCENE_GROUNDING_AZURE_OPENAI_API_VERSION =
  DPH_GROUNDING_AZURE_OPENAI_API_VERSION;
export const MIDSCENE_GROUNDING_AZURE_OPENAI_DEPLOYMENT =
  DPH_GROUNDING_AZURE_OPENAI_DEPLOYMENT;
export const MIDSCENE_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON =
  DPH_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON;
export const MIDSCENE_GROUNDING_USE_ANTHROPIC_SDK =
  DPH_GROUNDING_USE_ANTHROPIC_SDK;
export const MIDSCENE_GROUNDING_ANTHROPIC_API_KEY =
  DPH_GROUNDING_ANTHROPIC_API_KEY;
export const MIDSCENE_GROUNDING_VL_MODE = DPH_GROUNDING_VL_MODE;

/**
 * env keys declared but unused
 */
export const UNUSED_ENV_KEYS = [DPH_DANGEROUSLY_PRINT_ALL_CONFIG];

/**
 * env keys for debug or basic run
 * can not be override by overrideAIConfig
 */
export const BASIC_ENV_KEYS = [
  DPH_DEBUG_MODE,
  DPH_DEBUG_AI_PROFILE,
  DPH_DEBUG_AI_RESPONSE,
  DPH_RUN_DIR,
] as const;

export const BOOLEAN_ENV_KEYS = [
  DPH_CACHE,
  DPH_LANGSMITH_DEBUG,
  DPH_FORCE_DEEP_THINK,
  DPH_MCP_USE_PUPPETEER_MODE,
  DPH_MCP_ANDROID_MODE,
] as const;

export const NUMBER_ENV_KEYS = [
  DPH_CACHE_MAX_FILENAME_LENGTH,
  DPH_REPLANNING_CYCLE_LIMIT,
] as const;

export const STRING_ENV_KEYS = [
  OPENAI_MAX_TOKENS,
  DPH_ADB_PATH,
  DPH_ADB_REMOTE_HOST,
  DPH_ADB_REMOTE_PORT,
  DPH_ANDROID_IME_STRATEGY,
  DPH_IOS_DEVICE_UDID,
  DPH_IOS_SIMULATOR_UDID,
  DPH_REPORT_TAG_NAME,
  DPH_PREFERRED_LANGUAGE,
  MATCH_BY_POSITION,
  DPH_MCP_CHROME_PATH,
  DOCKER_CONTAINER,
] as const;

/**
 * Non model related env keys, used for globally controlling the behavior of Dark Pattern Hunter
 * Can not be override by agent.modelConfig but can be override by overrideAIConfig
 * Can be access at any time
 */
export const GLOBAL_ENV_KEYS = [
  ...BOOLEAN_ENV_KEYS,
  ...NUMBER_ENV_KEYS,
  ...STRING_ENV_KEYS,
] as const;

/**
 * Model related eve keys, used for declare which model to use.
 * Can be override by both agent.modelConfig and overrideAIConfig
 * Can only be access after agent.constructor
 */
export const MODEL_ENV_KEYS = [
  // model default
  DPH_MODEL_NAME,
  DPH_OPENAI_INIT_CONFIG_JSON,
  DPH_OPENAI_API_KEY,
  DPH_OPENAI_BASE_URL,
  DPH_OPENAI_USE_AZURE,
  DPH_OPENAI_SOCKS_PROXY,
  DPH_OPENAI_HTTP_PROXY,
  DPH_USE_AZURE_OPENAI,
  DPH_AZURE_OPENAI_SCOPE,
  DPH_AZURE_OPENAI_INIT_CONFIG_JSON,
  DPH_USE_ANTHROPIC_SDK,
  DPH_USE_VLM_UI_TARS,
  DPH_USE_QWEN_VL,
  DPH_USE_QWEN3_VL,
  DPH_USE_DOUBAO_VISION,
  DPH_USE_GEMINI,
  DPH_USE_VL_MODEL,
  ANTHROPIC_API_KEY,
  DPH_AZURE_OPENAI_ENDPOINT,
  DPH_AZURE_OPENAI_KEY,
  DPH_AZURE_OPENAI_API_VERSION,
  DPH_AZURE_OPENAI_DEPLOYMENT,
  DPH_VL_MODE,
  // model default legacy
  OPENAI_API_KEY,
  OPENAI_BASE_URL,
  OPENAI_USE_AZURE,
  ANTHROPIC_API_KEY,
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_KEY,
  AZURE_OPENAI_API_VERSION,
  AZURE_OPENAI_DEPLOYMENT,
  // VQA
  DPH_VQA_MODEL_NAME,
  DPH_VQA_OPENAI_SOCKS_PROXY,
  DPH_VQA_OPENAI_HTTP_PROXY,
  DPH_VQA_OPENAI_BASE_URL,
  DPH_VQA_OPENAI_API_KEY,
  DPH_VQA_OPENAI_INIT_CONFIG_JSON,
  DPH_VQA_OPENAI_USE_AZURE,
  DPH_VQA_USE_AZURE_OPENAI,
  DPH_VQA_AZURE_OPENAI_SCOPE,
  DPH_VQA_AZURE_OPENAI_KEY,
  DPH_VQA_AZURE_OPENAI_ENDPOINT,
  DPH_VQA_AZURE_OPENAI_API_VERSION,
  DPH_VQA_AZURE_OPENAI_DEPLOYMENT,
  DPH_VQA_AZURE_OPENAI_INIT_CONFIG_JSON,
  DPH_VQA_USE_ANTHROPIC_SDK,
  DPH_VQA_ANTHROPIC_API_KEY,
  DPH_VQA_VL_MODE,
  // PLANNING
  DPH_PLANNING_MODEL_NAME,
  DPH_PLANNING_OPENAI_SOCKS_PROXY,
  DPH_PLANNING_OPENAI_HTTP_PROXY,
  DPH_PLANNING_OPENAI_BASE_URL,
  DPH_PLANNING_OPENAI_API_KEY,
  DPH_PLANNING_OPENAI_INIT_CONFIG_JSON,
  DPH_PLANNING_OPENAI_USE_AZURE,
  DPH_PLANNING_USE_AZURE_OPENAI,
  DPH_PLANNING_AZURE_OPENAI_SCOPE,
  DPH_PLANNING_AZURE_OPENAI_KEY,
  DPH_PLANNING_AZURE_OPENAI_ENDPOINT,
  DPH_PLANNING_AZURE_OPENAI_API_VERSION,
  DPH_PLANNING_AZURE_OPENAI_DEPLOYMENT,
  DPH_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON,
  DPH_PLANNING_USE_ANTHROPIC_SDK,
  DPH_PLANNING_ANTHROPIC_API_KEY,
  DPH_PLANNING_VL_MODE,
  // GROUNDING
  DPH_GROUNDING_MODEL_NAME,
  DPH_GROUNDING_OPENAI_SOCKS_PROXY,
  DPH_GROUNDING_OPENAI_HTTP_PROXY,
  DPH_GROUNDING_OPENAI_BASE_URL,
  DPH_GROUNDING_OPENAI_API_KEY,
  DPH_GROUNDING_OPENAI_INIT_CONFIG_JSON,
  DPH_GROUNDING_OPENAI_USE_AZURE,
  DPH_GROUNDING_USE_AZURE_OPENAI,
  DPH_GROUNDING_AZURE_OPENAI_SCOPE,
  DPH_GROUNDING_AZURE_OPENAI_KEY,
  DPH_GROUNDING_AZURE_OPENAI_ENDPOINT,
  DPH_GROUNDING_AZURE_OPENAI_API_VERSION,
  DPH_GROUNDING_AZURE_OPENAI_DEPLOYMENT,
  DPH_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON,
  DPH_GROUNDING_USE_ANTHROPIC_SDK,
  DPH_GROUNDING_ANTHROPIC_API_KEY,
  DPH_GROUNDING_VL_MODE,
] as const;

export const ALL_ENV_KEYS = [
  ...UNUSED_ENV_KEYS,
  ...BASIC_ENV_KEYS,
  ...GLOBAL_ENV_KEYS,
  ...MODEL_ENV_KEYS,
] as const;

export type TEnvKeys = (typeof ALL_ENV_KEYS)[number];
export type TGlobalConfig = Record<TEnvKeys, string | undefined>;

export type TVlModeValues =
  | 'qwen-vl'
  | 'qwen3-vl'
  | 'doubao-vision'
  | 'gemini'
  | 'vlm-ui-tars'
  | 'vlm-ui-tars-doubao'
  | 'vlm-ui-tars-doubao-1.5';

export type TVlModeTypes =
  | 'qwen-vl'
  | 'qwen3-vl'
  | 'doubao-vision'
  | 'gemini'
  | 'vlm-ui-tars';

export interface IModelConfigForVQA {
  // model name
  [DPH_VQA_MODEL_NAME]: string;
  // proxy
  [DPH_VQA_OPENAI_SOCKS_PROXY]?: string;
  [DPH_VQA_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [DPH_VQA_OPENAI_BASE_URL]?: string;
  [DPH_VQA_OPENAI_API_KEY]?: string;
  [DPH_VQA_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [DPH_VQA_OPENAI_USE_AZURE]?: string;
  [DPH_VQA_USE_AZURE_OPENAI]?: string;
  [DPH_VQA_AZURE_OPENAI_SCOPE]?: string;
  [DPH_VQA_AZURE_OPENAI_KEY]?: string;
  [DPH_VQA_AZURE_OPENAI_ENDPOINT]?: string;
  [DPH_VQA_AZURE_OPENAI_API_VERSION]?: string;
  [DPH_VQA_AZURE_OPENAI_DEPLOYMENT]?: string;
  [DPH_VQA_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [DPH_VQA_USE_ANTHROPIC_SDK]?: string;
  [DPH_VQA_ANTHROPIC_API_KEY]?: string;
  // extra
  [DPH_VQA_VL_MODE]?: TVlModeValues;
}

export interface IModelConfigForPlanning {
  // model name
  [DPH_PLANNING_MODEL_NAME]: string;
  // proxy
  [DPH_PLANNING_OPENAI_SOCKS_PROXY]?: string;
  [DPH_PLANNING_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [DPH_PLANNING_OPENAI_BASE_URL]?: string;
  [DPH_PLANNING_OPENAI_API_KEY]?: string;
  [DPH_PLANNING_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [DPH_PLANNING_OPENAI_USE_AZURE]?: string;
  [DPH_PLANNING_USE_AZURE_OPENAI]?: string;
  [DPH_PLANNING_AZURE_OPENAI_SCOPE]?: string;
  [DPH_PLANNING_AZURE_OPENAI_KEY]?: string;
  [DPH_PLANNING_AZURE_OPENAI_ENDPOINT]?: string;
  [DPH_PLANNING_AZURE_OPENAI_API_VERSION]?: string;
  [DPH_PLANNING_AZURE_OPENAI_DEPLOYMENT]?: string;
  [DPH_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [DPH_PLANNING_USE_ANTHROPIC_SDK]?: string;
  [DPH_PLANNING_ANTHROPIC_API_KEY]?: string;
  // extra
  [DPH_PLANNING_VL_MODE]?: TVlModeValues;
}

export interface IModeConfigForGrounding {
  // model name
  [DPH_GROUNDING_MODEL_NAME]: string;
  // proxy
  [DPH_GROUNDING_OPENAI_SOCKS_PROXY]?: string;
  [DPH_GROUNDING_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [DPH_GROUNDING_OPENAI_BASE_URL]?: string;
  [DPH_GROUNDING_OPENAI_API_KEY]?: string;
  [DPH_GROUNDING_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [DPH_GROUNDING_OPENAI_USE_AZURE]?: string;
  [DPH_GROUNDING_USE_AZURE_OPENAI]?: string;
  [DPH_GROUNDING_AZURE_OPENAI_SCOPE]?: string;
  [DPH_GROUNDING_AZURE_OPENAI_KEY]?: string;
  [DPH_GROUNDING_AZURE_OPENAI_ENDPOINT]?: string;
  [DPH_GROUNDING_AZURE_OPENAI_API_VERSION]?: string;
  [DPH_GROUNDING_AZURE_OPENAI_DEPLOYMENT]?: string;
  [DPH_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [DPH_GROUNDING_USE_ANTHROPIC_SDK]?: string;
  [DPH_GROUNDING_ANTHROPIC_API_KEY]?: string;
  // extra
  [DPH_GROUNDING_VL_MODE]?: TVlModeValues;
}

export interface IModelConfigForDefault {
  // model name
  [DPH_MODEL_NAME]: string;
  // proxy
  [DPH_OPENAI_SOCKS_PROXY]?: string;
  [DPH_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [DPH_OPENAI_BASE_URL]?: string;
  [DPH_OPENAI_API_KEY]?: string;
  [DPH_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [DPH_OPENAI_USE_AZURE]?: string;
  [DPH_USE_AZURE_OPENAI]?: string;
  [DPH_AZURE_OPENAI_SCOPE]?: string;
  [DPH_AZURE_OPENAI_KEY]?: string;
  [DPH_AZURE_OPENAI_ENDPOINT]?: string;
  [DPH_AZURE_OPENAI_API_VERSION]?: string;
  [DPH_AZURE_OPENAI_DEPLOYMENT]?: string;
  [DPH_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [DPH_USE_ANTHROPIC_SDK]?: string;
  [DPH_ANTHROPIC_API_KEY]?: string;
  // extra
  [DPH_VL_MODE]?: TVlModeValues;
}

export interface IModelConfigForDefaultLegacy {
  // model name
  [DPH_MODEL_NAME]: string;
  // proxy
  [DPH_OPENAI_SOCKS_PROXY]?: string;
  [DPH_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [OPENAI_BASE_URL]?: string;
  [OPENAI_API_KEY]?: string;
  [DPH_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [OPENAI_USE_AZURE]?: string;
  [DPH_USE_AZURE_OPENAI]?: string;
  [DPH_AZURE_OPENAI_SCOPE]?: string;
  [AZURE_OPENAI_KEY]?: string;
  [AZURE_OPENAI_ENDPOINT]?: string;
  [AZURE_OPENAI_API_VERSION]?: string;
  [AZURE_OPENAI_DEPLOYMENT]?: string;
  [DPH_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [DPH_USE_ANTHROPIC_SDK]?: string;
  [ANTHROPIC_API_KEY]?: string;
  // extra
  [DPH_VL_MODE]?: TVlModeValues;
}

/**
 * - VQA: Visual Question Answering
 * - grounding：short for Visual Grounding
 * - planning: planning
 * - default: all except VQA、grounding、planning
 */
export type TIntent = 'VQA' | 'planning' | 'grounding' | 'default';

export type TModelConfigFn = (options: {
  intent: TIntent;
}) =>
  | IModelConfigForVQA
  | IModelConfigForPlanning
  | IModeConfigForGrounding
  | IModelConfigForDefault;

/**
 * UITarsModelVersion enum - must match @ui-tars/shared package values exactly
 * Used for UI-TARS model versioning
 */
export enum UITarsModelVersion {
  V1_0 = '1.0',
  V1_5 = '1.5',
  DOUBAO_1_5_15B = 'doubao-1.5-15B',
  DOUBAO_1_5_20B = 'doubao-1.5-20B',
}

/**
 * Valid raw values for VL_MODE environment variable
 */
export const VL_MODE_RAW_VALID_VALUES = [
  'qwen-vl',
  'qwen3-vl',
  'doubao-vision',
  'gemini',
  'vlm-ui-tars',
  'vlm-ui-tars-doubao',
  'vlm-ui-tars-doubao-1.5',
] as const;

/**
 * Model configuration interface with named properties
 * This is the runtime model config used by the application
 */
export interface IModelConfig {
  // Model identification
  modelName: string;
  modelDescription: string;

  // Source tracking
  from: 'env' | 'modelConfig' | 'legacy-env';
  intent: TIntent;

  // Proxy settings
  socksProxy?: string;
  httpProxy?: string;

  // OpenAI configuration
  openaiBaseURL?: string;
  openaiApiKey?: string;
  openaiExtraConfig?: Record<string, unknown>;
  openaiUseAzureDeprecated?: boolean;

  // Azure OpenAI configuration
  useAzureOpenai?: boolean;
  azureOpenaiScope?: string;
  azureOpenaiKey?: string;
  azureOpenaiEndpoint?: string;
  azureOpenaiDeployment?: string;
  azureOpenaiApiVersion?: string;
  azureExtraConfig?: Record<string, unknown>;

  // Anthropic configuration
  useAnthropicSdk?: boolean;
  anthropicApiKey?: string;

  // Vision Language Model settings
  vlMode?: TVlModeTypes;
  vlModeRaw?: string;
  uiTarsVersion?: UITarsModelVersion;
  uiTarsModelVersion?: UITarsModelVersion;
}
